theme: sufficiency-hugo-theme
enableRobotsTXT: true
removePathAccents: true
params:
  zotero: 
    group: '5675191'
    collection: '53VFAINU'
  summary:
    position: hero
  search:
    active: true
languages:
  en:
    taxonomies:
      tag: tags
