theme: sufficiency-hugo-theme
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true
languages:
  en:
    taxonomies:
      geographical-scope: geographical-scopes
      human-need: human-needs
      natural-resource-impacted: natural-resources-impacted
      planetary-boundary-impacted: planetary-boundaries-impacted
      scientific-discipline: scientific-disciplines
      sub-sector: sub-sectors
