theme: sufficiency-hugo-theme
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true
languages:
  en:
    taxonomies:
      geographical-scope: geographical-scopes
      scientific-discipline: scientific-disciplines
